### PR TITLE
Check user membership in related org

### PR DESCRIPTION
**Pull request by destitutus**
Server api allow empty value - check in all teams

see https://codio.myjetbrains.com/youtrack/issue/codio-7494

### CODE REVIEW

**Comment by MaximKraev** [comment]
:+1:

**Comment by AndreyNikitin** [comment]
maybe better call server method isOrgMember?

**Comment by destitutus** [comment]
> maybe better call server method isOrgMember?

could you explain your point please

server api want changed at all(it allow to pass `null` values - it mean mapping all teams in organization to map `{'teamId' => bool value is member in team}` and fixed wrong assert on `node-codio` side

**Comment by MaximKraev** [comment]
@AndreyNikitin, My opinion is: I think it is not critical now to add a new method, we can leave with the isMemberOf solution for now, feel free to create an issue, to improve the code when you have a free minute.

**Comment by vvlevykin** [comment]
I think what @AndreyNikitin meant is that it should be possible to pass `__all_members__` to make `isMemberOf` consistent with other organization methods.

**Comment by destitutus** [comment]
> meant is that it should be possible to pass `__all_members__` to make isMemberOf consistent with other organization methods.

apollo don't know about `__all_members__` team nothing. Not sure it is a good idea.
server api of `is memberOf` accept `null` value - assertion in node-codio is incorrect

**Comment by MaximKraev** [comment]
lets have a discussion after the standup, this PR has nothing to do with consistency, it just a fix for the node-client null argument allowance.

**Comment by AndreyNikitin** [comment]
:+1:

**Pull request merged**
